Make questions more consistent and unique
rhboot/shim-review pull request #207
Opened 2021-09-21 13:38 UTC by tedbrandston

The current workflow requires filling out two pretty similar questionnaires (the one in the README, and the one in the ISSUE_TEMPLATE). Some of the questions are similar-but-different between the two, and are sometimes confusingly formatted or worded. I've attempted to make things a little clearer/more consistent, but I'm sure there's things here done a certain way for reasons I'm not aware of, so I'm very open to feedback.

Some specifics:
* I've made the header-style consistent between the README and ISSUE_TEMPLATE
  * README was using a [horizontal rule](https://daringfireball.net/projects/markdown/syntax#hr) (`---`) before a [setext-style header](https://daringfireball.net/projects/markdown/syntax#header) (also `---`). Github seems to format that nicely until you try to have a list in there (see the two questions after [this](https://github.com/rhboot/shim-review/blob/d2f40a40f281d5ae482dfa7cc73ac11fd187e182/README.md#if-bootloader-shim-loading-is-grub2-is-cve-2020-14372-cve-2020-25632cve-2020-25647-cve-2020-27749-cve-2020-27779-cve-2021-20225-cve-2021-20233cve-2020-10713-cve-2020-14308-cve-2020-14309-cve-2020-14310-cve-2020-14311cve-2020-15705-and-if-you-are-shipping-the-shim_lock-module-cve-2021-3418) one).
  * ISSUE_TEMPLATE was using [atx-style headers](https://daringfireball.net/projects/markdown/syntax#header), but seems to vary between `#####` and `######`, probably because it's hard to spot the difference at a glance.
  * I'm standardizing on the combination of `###` (easier to spot the difference between `##` and `###` or `###` and `####` than to spot the difference between `####` and `#####` or `#####` and `######`) and horizontal rules (`---`) to box in lists, since lists don't work in headers.
* Questions were also inconsistent ending with a colon or a question mark. I've standardized on question mark.
* For questions that differ between the two questionnaires I've looked through the history to try to understand the divergence and merge them correctly. 

While I initially tried to update these questions without changing the fundamental workflow or file layout, it ended up seeming like all the questions should be moved to one place so I went for it. ~That's in a single commit so it's easy to drop. I do see the potential for additional workflow/layout improvements, and if there's interest I'm happy to outline some of my thoughts in a comment.~

-------------------------------------------------------------------------------

Not sure how familiar with the Github UI everyone is (and I always have to poke around to find this): to view the rendered markdown you can use the ellipses next to a given file -> "View File".

2021-09-21 13:39 UTC, tedbrandston commented on README.md
> +### Please specifically confirm that you add a vendor specific SBAT entry for SBAT header in each binary that supports SBAT metadata ( grub2, fwupd, fwupdate, shim + all child shim binaries ) to shim
I'm not clear what's being referred to by "shim review doc" here. I think it's the readme, but I also think this is asking you to confirm that you've listed some SBAT stuff in your readme, while the readme previously said nothing about sbat.

2021-09-21 13:41 UTC, tedbrandston commented on README.md
> -If bootloader, shim loading is, GRUB2: is CVE-2020-14372, CVE-2020-25632,
This, combined with the next two questions, seems like a multi-part "If you're loading grub2". This is now moved to the readme [here](https://github.com/rhboot/shim-review/pull/207/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R128-R145). Does it seem like I've gotten the meaning right?

2021-09-21 13:42 UTC, tedbrandston commented on README.md
> +### Is upstream commit [75b0cea7bf307f362057cc778efe89af4c615354 "ACPI: configfs: Disallow loading ACPI tables when locked down"](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/co
When this question was introduced it only asked for one commit in the ISSUE_TEMPLATE, but two commits in the README. I don't know why, so I've put both here. That might be wrong.

2021-09-21 13:44 UTC, tedbrandston commented on ISSUE_TEMPLATE.md
> +-------------------------------------------------------------------------------
I've left these two questions in as a hopefully-helpful "at-a-glance" thing, but this info is also normally in the title so it might be fine to drop these last two.

2021-09-21 13:45 UTC, tedbrandston commented on ISSUE_TEMPLATE.md
On [line 3](https://github.com/rhboot/shim-review/pull/207/files#diff-e5aa817955e06f89b32731f49a1ccf2bcd70eb907e023ca0766899cf64d7f9aaR3) it says to include a link to your fork of shim-review. Should we have a specific question here so it's clear where to put it/what format?

2021-09-22 13:21 UTC, tedbrandston commented
> I don't think we'd want to do that without further discussion.

I definitely didn't expect this to go in without some discussion. I was hoping this could act as a bit of a strawman proposal to help me understand the best places for different questions/what the structure is intended to be.

> You seem to have deleted most of the questions, and I'm not immediately sure why

All the questions should have been moved to README.md, if there are any that have been dropped it's accidental.

If it's important to have the questions in the ISSUE_TEMPLATE.md, then is there any reason to have them in the README? I can have the ISSUE_TEMPLATE be the place where all the questions live.

Alternatively, if it's important to have the questions divided between the README and the ISSUE_TEMPLATE, which ones should go where? Are there any guidelines for which kinds of info belong in the README vs. the ISSUE_TEMPLATE?

> If this is going to be merged, the commit messages will also need cleaning up

Sure thing. I generally try to ~match the existing commits in a repo. I've skimmed the guide you linked and, just so I'm clear on what you'd like improved, I think you're asking me to:
* Limit the subject lines to 50 chars
* Wrap the body at 72 chars
* Do a better job explaining _why_ I'm making some of these changes (I think I've done a decent job on covering _what_ I've changed, though I won't be offended if you say otherwise). I considered including links to commits where specific questions were introduced & where they diverged, but I was concerned that would feel like I was calling specific contributors out. If there are specific commits that are especially unclear or that you want more detail in, please point those out.

I believe I've already done the other things mentioned in the guide.

2021-09-22 15:34 UTC, frozencemetery commented
Ted Brandston ***@***.***> writes:

> If it's important to have the questions in the ISSUE_TEMPLATE.md, then
> is there any reason to have them in the README? I can have the
> ISSUE_TEMPLATE be the place where all the questions live.

I can't speak for others, but for myself as a potential reviewer the
questions need to be in ISSUE_TEMPLATE otherwise people won't fill them
out :)

2021-09-22 19:08 UTC, julian-klode commented
I see myself on the other side of the spectrum. Some people don't commit their answers for the issue template, so you can't compare against previous submissions easily.

2021-09-22 19:57 UTC, tedbrandston commented
So, it doesn't have to be either/or.

If the problem I'm trying to solve is the maintenance burden of having two copies of the questions (and the confusion submitters face when those diverge), and some reviewers would like to look at answers in-repo while others would like them to be in the submitted issue, it seems like there are multiple options that can satisfy that:
* Remove all questions from the issue template, and have the final checklist item be something like "Copy-paste the contents of your README below". 
* Even more extreme: drop the ISSUE_TEMPLATE, have all the instructions/reminders in the README, including something like "When submitting paste the entirety of this document into the issue."
* Use symlinks such that README points to ISSUE_TEMPLATE or vice versa. Github handles this fine ([I tried it](https://github.com/tedbrandston/readme-symlink-test)). The instructions in README could move to something like SUBMISSION_INSTRUCTIONS.md, so that everything/almost everything in the README makes sense in the ISSUE_TEMPLATE too. There would be a single file in which to update questions, and it would be easy for reviewers to copy-paste their submission into the box.

There are probably other solutions. I don't have any particular preference, but am happy to do the work of moving things around however y'all see fit.

2021-12-06 22:00 UTC, frozencemetery commented
Having thought about this some more, I think I'm going to contradict my past self and agree with Julian - the README should be the source of truth.  Apologies for being difficult, but at least you've got reviewers agreeing now :)

2021-12-07 19:03 UTC, tedbrandston commented
Thanks for the update! I don't think you're being difficult at all, reasonable people can have different opinions and views that change over time.

I think I'd like to do two things in parallel:
1. Update this PR with a slightly updated workflow:
    - Make it clear that the README should be the source of truth
    - Reduce the ISSUE_TEMPLATE to be the checklist plus a field linking to the user's fork
2. Work in smaller PRs to move towards this final state.

Updating this PR will help make sure we're heading in the right direction. Having smaller PRs (e.g. getting https://github.com/rhboot/shim-review/pull/209 or some portion of it mergeable) should help keep things improving in small ways even if the bigger picture isn't settled.

Does that sound okay?

2021-12-07 20:41 UTC, frozencemetery commented
Sure - if you feel more comfortable in smaller PRs that's probably okay, but I slightly prefer having related commits grouped together in a review unit if possible.

2022-03-14 19:31 UTC, tedbrandston commented
Back to spending some time thinking about this. I have two more changes I think I should make:

If we do what's shown in this PR, the tag in another repo is the only thing that's being approved. There's no guarantee that I see preventing someone from just changing where that tag points on their end. I should probably add back at least the SHA of the shim binary being signed to be put in the ISSUE_TEMPLATE.

As a follow on to that: In the ISSUE_TEMPLATE all of the checklist items but one are reminders to do things that the README asks for. That one is "link to your code branch...". It looks like some issues link to that one thing directly in the checklist, some issues link to each of the things in the checklist, and some don't seem to understand what's supposed to be filled in. I wonder if the link to the tag and the SHA should be separated slightly as "things to fill in" rather than boxes to check.

2022-03-22 17:08 UTC, frozencemetery requested changes
In general I like where this is going - just a couple things.

2022-03-22 17:08 UTC, frozencemetery commented on README.md
> +### Please specifically confirm that you add a vendor specific SBAT entry for SBAT header in each binary that supports SBAT metadata ( grub2, fwupd, fwupdate, shim + all child shim binaries ) to shim
It seems like we can safely drop "to shim review doc" (and maybe clean the question up a bit too).

2022-03-22 17:08 UTC, frozencemetery commented on README.md
> +* if you are shipping the shim_lock module: CVE-2021-3418
Maybe put the "if" clause in parentheses to emphasize that this only affects some cases?

2022-03-22 17:08 UTC, frozencemetery commented on README.md
> +### If shim is loading GRUB2 bootloader and your previously released shim booted a version of grub affected by any of the following CVEs:
This drops mention of the month/year these go with.  I suspect it will be easier for folks to remember "July 2020 grub2 CVE list" than what each of these are :)

2022-03-22 17:09 UTC, frozencemetery commented on README.md
> -If bootloader, shim loading is, GRUB2: is CVE-2020-14372, CVE-2020-25632,
I think so, yes.

2022-03-22 17:10 UTC, frozencemetery commented on ISSUE_TEMPLATE.md
> -### Were your old SHIM hashes provided to Microsoft ?
(To be clear, I'm not taking a position on whether it should be preserved, but I didn't see it called out anywhere.)

2022-03-23 13:16 UTC, tedbrandston commented on ISSUE_TEMPLATE.md
> -### Were your old SHIM hashes provided to Microsoft ?
Yeah, the history of this one wasn't super clear. If anyone wants to weigh in on whether/how this should be preserved:
1. Added in fe5386fa912ca84b4cc1bbdcf29ef03d81a6fee6
   * in ISSUE_TEMPLATE as "Were your old SHIM hashes provided to Microsoft ?"
   * in README as part of an "If bootloader, shim loading is, grub2, and...": "were old shims hashes provided to Microsoft for verification and to be added to future DBX update ?"
2. Then it gets dropped from ISSUE_TEMPLATE in 87c0eca462f9e1ccc7ebf91a5c8e526c7cd5e2a2
3. But readded in da3ecfd72a2d88cfa1adbc83ce3989506b978a60

On this branch the "readme version" is preserved [here](https://github.com/rhboot/shim-review/pull/207/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R100) -- I assumed since they were added at the same time they should be considered basically the same question at different levels of detail and opted to keep the more detailed version.

2022-03-23 13:35 UTC, tedbrandston commented on README.md
> +* if you are shipping the shim_lock module: CVE-2021-3418
You're suggesting:
```
...
* CVE-2020-14311
* CVE-2020-15705
* (if you are shipping the shim_lock module: CVE-2021-3418)
```

?

2022-03-23 13:53 UTC, tedbrandston commented on README.md
> +### Please specifically confirm that you add a vendor specific SBAT entry for SBAT header in each binary that supports SBAT metadata ( grub2, fwupd, fwupdate, shim + all child shim binaries ) to shim
Since github seems to have lost the association, fixed [here](https://github.com/rhboot/shim-review/pull/207/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R158)

2022-03-23 13:55 UTC, tedbrandston commented on README.md
> +### If shim is loading GRUB2 bootloader and your previously released shim booted a version of grub affected by any of the following CVEs:
[fixed](https://github.com/rhboot/shim-review/pull/207/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R84)

2022-03-23 18:45 UTC, frozencemetery commented on ISSUE_TEMPLATE.md
> -### Were your old SHIM hashes provided to Microsoft ?
Aha, okay.  Given (2) I think it makes sense to drop.

2022-03-23 18:46 UTC, frozencemetery commented on README.md
> +* if you are shipping the shim_lock module: CVE-2021-3418
Or even "CVE-2021-3418 (if you are shipping...)"

2022-03-24 19:18 UTC, frozencemetery approved these changes

2022-04-21 18:20 UTC, tedbrandston commented
Does this need any additional review?

2022-04-21 19:32 UTC, merged