Make formatting of README and ISSUE_TEMPLATE match
rhboot/shim-review pull request #209
Opened 2021-09-29 19:36 UTC by tedbrandston

This changes the headers and horizontal rules to be the same style in both documents.

There are two goals:
* Make it a little easier for submitters to copy answers from README  (where the docs ask us to commit them) to the github issue
* Hopefully make it easier for maintainers to update the questions, since there's now only one format to match

I chose this style in an attempt to capture the benefits of each of the styles currently in use.
* README was using a [horizontal rule](https://daringfireball.net/projects/markdown/syntax#hr) (`---`) before a [setext-style header](https://daringfireball.net/projects/markdown/syntax#header) (also `---`). Github seems to format that nicely until you try to have a list in there (see the two questions after [this](https://github.com/rhboot/shim-review/blob/d2f40a40f281d5ae482dfa7cc73ac11fd187e182/README.md#if-bootloader-shim-loading-is-grub2-is-cve-2020-14372-cve-2020-25632cve-2020-25647-cve-2020-27749-cve-2020-27779-cve-2021-20225-cve-2021-20233cve-2020-10713-cve-2020-14308-cve-2020-14309-cve-2020-14310-cve-2020-14311cve-2020-15705-and-if-you-are-shipping-the-shim_lock-module-cve-2021-3418) one).
* ISSUE_TEMPLATE was using [atx-style headers](https://daringfireball.net/projects/markdown/syntax#header), but seems to vary between `#####` and `######`, probably because it's hard to spot the difference at a glance.

I'm standardizing on the combination of `###` to indicate which lines to header-ify (It's easier to spot the difference between
`##` and `###` or `###` and `####` than to spot the difference between `####` and `#####` or `#####` and `######`) along with horizontal rules (`---`) to box in lists and other non-header text, since lists don't work in headers.

This was originally posted as part of https://github.com/rhboot/shim-review/pull/207. I'm attempting to break out individual commits from that PR.

### For example:
![image](https://user-images.githubusercontent.com/1101979/135333999-76abfdf4-0101-4368-8a39-0cd9a18e46ed.png)
becomes 
![image](https://user-images.githubusercontent.com/1101979/135334958-8b8ed60c-9283-4445-8f73-01dab89002bd.png)

and 
![image](https://user-images.githubusercontent.com/1101979/135336216-fb1a7ce2-3a7a-4f63-88ae-fec7ab50abb2.png)
becomes
![image](https://user-images.githubusercontent.com/1101979/135336159-fc6d71d5-ee50-4732-8af5-7d02f68ff353.png)

2021-12-07 20:42 UTC, frozencemetery requested changes
(Needs rebased)

2022-02-10 19:32 UTC, frozencemetery approved these changes

2022-02-14 14:25 UTC, tedbrandston commented
Do I need to add an additional reviewer, or anything else?

2022-02-15 19:15 UTC, frozencemetery commented
No, everything's fine unless someone else has feedback.  I prefer to let things sit about a week in case someone does, and interpret silence there as "no objection".

2022-02-22 16:27 UTC, merged