Ask about the NX bit and point to NX signing exception
rhboot/shim-review pull request #359
Opened 2023-12-11 11:44 UTC by julian-klode

Microsoft issued an exception for signing shims without NX bits set. As reviewers should be aware already, shims should only be signed with the NX bit on if the entire boot stack is NX compatible. The final kernel support landed in 6.7 mainline AFAIUI, and the grub work still remains a bit WIP.

But let's ask people specifically about this, and if they do submit NX shim to explain what testing they did to ensure compliance. Not everyone uses grub and their loaders may be NX-compatible and they might have kernels ready now if they're bleeding edge.

2023-12-11 12:35 UTC, aronowski requested changes
I don't think it's yet the right time to ask people about the compliance and testing thing.

I've been having discussions with people who are way more oriented in the low-level ecosystem, both in regard to firmware, kernel development, among others, and full-stack compatibility around NX is still a thing that we're quite unsure about. We've had some proposals like custom patches in the kernel that will test if an illegal operation would be properly handled and prohibited or if we could test on specifically tailored OVMF builds or certain hardware both consumer-grade and in the cloud (not saying the details, as I'm not here to advertise them).

I think that if this question is meant to be there, a required set of patches or certain versions of GRUB2 and the kernel shall be asked about instead. Especially since your comment mentions

> The final kernel support landed in 6.7 mainline AFAIUI, and the grub work still remains a bit WIP.

and I think that you **do** follow the development of those components closely - although other people may not. I myself am not subscribed e.g. to the kernel mailing lists.

In regard to what I just wrote, I'm thinking of an even more inclusive approach. Maybe some people will not know, how to test the shim binary for NX support? I'd suggest some hints like using user-friendly tools to inspect the binary. Maybe, for instance, @hasherezade's [PE-bear](https://github.com/hasherezade/pe-bear), like here:

![pe-bear](https://github.com/rhboot/shim-review/assets/100043949/24b7ef52-290f-4451-8ee8-e2437d82df12)

I'd also write a hint, where to click, so people who are not familiar with the PE format will have an easier time and more motivation to learn and contribute.

2023-12-11 12:44 UTC, julian-klode commented
@aronowski You're demanding a bit much. Nobody knows what patches are needed at this point, and whether what's out there so far actually works.

Hence adding this question to tell people they shouldn't be submitting shims with the NX bit set while keeping the future a bit open.

2023-12-11 13:08 UTC, aronowski commented
@julian-klode 

> You're demanding a bit much

That's exactly the point. ;-)

Historically people, myself included, were having doubts about if we understand the questions and requirements correctly. Hence why I'd like to make them more precise to avoid ambiguity.

> Hence adding this question to tell people they shouldn't be submitting shims with the NX bit set while keeping the future a bit open.

Yes! In that case I'd still slightly rewrite it, maybe (the first idea that came to my mind and will not be the most optimal in the world) like:

*If your shim binary has the NX bit set, what testing has been done to ensure the whole bootchain is NX-compatible?*

And later on I'd create myself an issue to write some loose notes about NX support to gather the knowledge in one place, preferably in the `docs/` directory.

> And looking at the PE binary only tells you if you have the flag set not whether it works

That's right - as said earlier, we've been struggling with defining, what is the correct support verification method. I don't know if @steve-mcintyre sent you a link to *THAT* document, where certain notes were written, but I'm not allowed to link to it in public.

> we certainly shouldn't point people at freaking Windows applications for submitting Linux boot stuff

That's right - it's exactly why I suggested a user-friendly cross-platform Qt application, which I screenshooted on a Fedora 38.

Furthermore, this software may come in handy for people, who don't submit precisely Linux boot stuff - as far as I can see, [this submission](https://github.com/rhboot/shim-review/issues/353), where I commented and hour ago, uses `bootmgfw.efi`, A.K.A. Windows Boot Loader as the second-stage bootloader.

> And if they don't know, they should not be submitting shims in the first place - it's clear evidence they lack skills that would enable them to do a reasonable job at maintaining boot loaders.

That's why we've been discussing, how to make the environment more inclusive to newcomers, so they have easier time learning all this. A welcoming atmosphere is vital, but so is documentation and a flow, that creates something like a "sales funnel", rather than having people reverse-engineer these processes.

---

Please, create an issue on the "loose notes" documentation I was writing about earlier, and write, what should I include, so the most important information is right there. You follow the development closely, so you can tell me, where should I look for information and what mailing lists to subscribe to.

2023-12-11 13:09 UTC, julian-klode commented
Basically the entire point of the question is that you can't answer it affirmatively because nobody knows how to yet, such that you can ban bad faith submitters who still do affirmatively answer it.

2023-12-11 13:51 UTC, kukrimate commented
@aronowski 

I think the goal of Julian's question isn't that "we want people signing NX shims and we are ensuring you comply with the requirements", but instead it is that "you cannot practically have working NX boot stacks right now, so we're checking that you aren't accidentally enabling the compat bit".

I think linking to Microsoft documentation is very much reasonable in this case given they are the signing authority setting the requirements in the first place. I don't think it would be wise to  endorse specific tools, especially not something like PE-bear which isn't part of the standard toolchain we use for buildings these things.

2023-12-11 16:42 UTC, aronowski commented
@kukrimate,

> I think the goal of Julian's question isn't that "we want people signing NX shims and we are ensuring you comply with the requirements", but instead it is that "you cannot practically have working NX boot stacks right now, so we're checking that you aren't accidentally enabling the compat bit".

That! :+1: 

I wrote a quick proposal, what can be done, so when this feature gets merged, it is future-proof, and in reasonably clear wording, so people don't get scared or confused.

Though this proposal still doesn't account for hints like: *Implementing the complete bootchain as NX-compatible is hard - make sure you're either sure it works as intended or answer with 'no' and use a shim without the NX bit - there's no penalty for that*.

As far as I can see, there was [a manual intervention required](https://github.com/rhboot/shim-review/issues/353#issuecomment-1850417113) due to how it is today. Why not make it a thing and provide at least a quick explanation for people who apply?

2023-12-11 17:44 UTC, jsetje commented
The long term goal for NX at boot time is certainly to get it enabled by default on all platforms. This also means to eventually not load anything not tagged as NX compat in any sort of a fall back compatibility mode. So I do think there will be a point where non-NX shims shouldn't be signed anymore. However, that moment is clearly not here just yet. By the same notion, I we should all be looking at what needs to be done to get ready for it now.

2024-02-05 14:50 UTC, THS-on commented
Lets merge this question before we further go through the 15.8 submissions. Before the exception was granted, the communication was unclear when NX needs to be enabled. Now this should be enough for submitters to decide what kind of shim they need to submit.

2024-02-05 16:28 UTC, merged

2024-02-05 16:28 UTC, julian-klode commented
ack